export type Food = {
  Id: number;
  "Categoria do alimento": string;
  "Descrição dos alimentos": string;
  Umidade: number;
  "Energia/kcal": number;
  "Energia/kj": number;
  "Proteína/g": number;
  "Lipídeos/g": number;
  "Colesterol/mg": string | "NA";
  "Carboidrato/g": number;
  "Fibra.Alimentar/g": number;
  "Cinzas/g": number;
  "Cálcio/mg": number;
  "Magnésio/mg": number;
  "Manganês/mg": number;
  "Fósforo/mg": number;
  "Ferro/mg": number;
  "Sódio/mg": number;
  "Potássio/mg": number;
  "Cobre/mg": number;
  "Zinco/mg": number;
  "Retinol/mcg": string | "NA";
  "RE/mcg": string | "NA";
  "RAE/mcg": string | "NA";
  "Tiamina/mg": number;
  "Riboflavina/mg": number;
  "Piridoxina/mg": number;
  "Niacina/mg": number;
  "Vitamina.C/mg": string | "NA";
};
